---
- name: Configure RHEL 10 Web Server
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy custom index.html
      ansible.builtin.copy:
        content: |
          <html>
          <head><title>DevOps Lab</title></head>
          <body>
            <h1>Welcome to My DevOps Web Server!</h1>
            <p>Deployed via Terraform + Ansible on RHEL 10</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

