---
- name: Configure time synchronization using RHEL System Role
  hosts: localhost
  become: yes
  roles:
    - role: redhat.rhel_system_roles.timesync
      timesync_ntp_servers:
        - hostname: 0.rhel.pool.ntp.org
          iburst: true
        - hostname: 1.rhel.pool.ntp.org
          iburst: true
      timesync_manage_chrony: true
